# --- Publications Schema

# --- !Ups

CREATE TABLE publications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(250) NOT NULL UNIQUE,
  content TEXT NOT NULL,
  excerpt VARCHAR(500),
  cover_image VARCHAR(500),
  category VARCHAR(100) NOT NULL,
  tags VARCHAR(500),
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  view_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at TIMESTAMP,
  reviewed_by BIGINT,
  reviewed_at TIMESTAMP,
  rejection_reason TEXT,
  
  CONSTRAINT fk_publication_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_publication_reviewer FOREIGN KEY (reviewed_by) REFERENCES admins(id) ON DELETE SET NULL,
  CONSTRAINT chk_status CHECK (status IN ('draft', 'pending', 'approved', 'rejected'))
);

CREATE INDEX idx_publications_user_id ON publications(user_id);
CREATE INDEX idx_publications_status ON publications(status);
CREATE INDEX idx_publications_category ON publications(category);
CREATE INDEX idx_publications_slug ON publications(slug);
CREATE INDEX idx_publications_published_at ON publications(published_at DESC);
CREATE INDEX idx_publications_created_at ON publications(created_at DESC);

# --- !Downs

DROP TABLE IF EXISTS publications CASCADE;
